name: listen webhooks

on: [workflow_dispatch]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
    - name: Install requests
      run: |
        pip install flask
    - name: Test with pytest
      run: |
        export FLASK_APP=main.py
        python -m flask run
