name: Python application

on: 
  workflow_dispatch:
    inputs: 
      numOctocats:
        description: 'Number of Octocats'
        required: false
        default: '1'
      octocatEyeColor:
        description: 'Eye color of the Octocats'
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
    - name: Install requests
      run: |
        pip install requests
    - name: Test with pytest
      run: |
        python trigger_webhooks.py
